general:
  debug: true
  dryrun: false
  trace: true
  loglevel: logging.DEBUG
  loops: 1
  interval: 10

vpoller:
  endpoint: tcp://10.10.15.2:8080
  vc_host: vzbx-vc01

zabbix:
  url: https://10.10.15.2/zabbix
  username: Admin
  password: zabbix
  hostgroup: FNT Command
  template: Template FNT Virtual Server
  proxy: zabbix-proxy-sqlite3

command:
  url: http://10.10.15.100:8080
  username: do
  password: JcW8p43M7xSR6b

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s:%(module)s:%(name)s:%(levelname)s:%(message)s'
    default:
      format: '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stderr
    file:
      class: logging.FileHandler
      level: ERROR
      formatter: simple
      filename: <defined_in_code.log>
    wsgi:
      class: logging.StreamHandler
      stream: ext://flask.logging.wsgi_errors_stream
      formatter: simple
  loggers:
    vfzsync:
      level: DEBUG
      handlers: [file, wsgi]
      propagate: no
    vfzlib:
      level: DEBUG
      handlers: [console, file, wsgi]
      propagate: no
    __main__:
      level: DEBUG
      handlers: [console, file]
      propagate: no
    werkzeug:
      level: WARN
      handlers: [wsgi]
      propagate: no
    gunicorn:
      level: DEBUG
      handlers: [wsgi]
      propagate: no
    gunicorn.access:
      level: WARN
      handlers: [wsgi]
      propagate: no
    gunicorn.error:
      level: INFO
      handlers: [wsgi]
      propagate: no
    pyzabbix:
      level: INFO
      handlers: [file, wsgi]
      propagate: no
    requests.packages.urllib3:
      level: WARN
      handlers: [file, wsgi]
      propagate: yes
  root:
    level: WARN
    handlers: [console, file, wsgi]