general:
  debug: true
  dryrun: true
  trace: true
  loops: 1
  interval: 10

vpoller:
  endpoint: tcp://10.10.15.2:8080
  vc_host: vzbx-vc01

zabbix:
  url: https://10.10.15.2
  username: Admin
  password: zabbix
  hostgroup: FNT Command
  template: Template FNT Virtual Server
  proxy: zabbix-proxy-sqlite3

command:
  url: http://10.10.15.100:8080
  username: do
  password: JcW8p43M7xSR6b

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s:%(name)s:%(levelname)s:%(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stderr
    file:
      class: logging.FileHandler
      level: ERROR
      formatter: simple
      filename: <defined_in_code.log>
  loggers:
    vfzsync:
      level: DEBUG
      handlers: [console, file]
      propagate: no
    __main__:
      level: DEBUG
      handlers: [console, file]
      propagate: no
    vfzlib:
      level: DEBUG
      handlers: [console, file]
      propagate: no
    pyzabbix:
      level: INFO
      handlers: [console, file]
      propagate: no
    requests.packages.urllib3:
      level: WARN
      handlers: [console, file]
      propagate: yes

  root:
    level: WARN
    handlers: [console, file]